from string import Template

class EmailTemplates:
    
    ERROR_ALERT = Template("""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>FrankTech Error Alert</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; padding: 20px; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
            .header { border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; margin-bottom: 20px; }
            .logo { font-size: 24px; font-weight: bold; color: #0f172a; display: flex; align-items: center; gap: 8px; }
            .logo span { color: #06b6d4; }
            .severity-critical { background: #fee2e2; color: #991b1b; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
            .severity-error { background: #fef3c7; color: #92400e; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
            .severity-warning { background: #fef9c3; color: #713f12; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
            .error-box { background: #f1f5f9; padding: 16px; border-radius: 8px; margin: 16px 0; overflow-x: auto; }
            .error-box code { font-family: 'Courier New', monospace; font-size: 13px; white-space: pre-wrap; }
            .fix-box { background: #ecfdf5; border: 1px solid #10b981; padding: 16px; border-radius: 8px; margin: 16px 0; }
            .fix-box code { font-family: 'Courier New', monospace; font-size: 13px; }
            .button { display: inline-block; background: #06b6d4; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; margin-top: 16px; }
            .button:hover { background: #0891b2; }
            .footer { margin-top: 20px; padding-top: 20px; border-top: 2px solid #f1f5f9; color: #64748b; font-size: 14px; text-align: center; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <div class="logo">
                    🚀 <span>FrankTech</span> Intelligence
                </div>
            </div>
            
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
                <h2 style="margin: 0; color: #0f172a;">$error_type</h2>
                <span class="$severity_class">$severity</span>
            </div>
            
            <p style="color: #475569; font-size: 16px; margin-bottom: 4px;">
                <strong>Message:</strong> $error_message
            </p>
            
            <div style="margin: 8px 0 12px 0; color: #64748b; font-size: 14px;">
                <span>📁 Project: $project_name</span>
                <span style="margin-left: 16px;">🕐 $time</span>
                <span style="margin-left: 16px;">📌 Error #$error_id</span>
            </div>
            
            <div class="error-box">
                <strong style="display: block; margin-bottom: 8px; color: #0f172a;">🔍 Stack Trace</strong>
                <code>$stack_trace</code>
            </div>
            
            $fix_content
            
            <div style="margin-top: 20px;">
                <a href="$dashboard_url/errors/$error_id" class="button">View in Dashboard →</a>
            </div>
            
            <div class="footer">
                <p>This alert was automatically generated by FrankTech Intelligence.</p>
                <p style="font-size: 12px;">You can manage your notification preferences in <a href="$dashboard_url/settings" style="color: #06b6d4;">Settings</a>.</p>
            </div>
        </div>
    </body>
    </html>
    """)
    
    TEST_EMAIL = Template("""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>FrankTech - Email Test</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; padding: 20px; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
            .logo { font-size: 24px; font-weight: bold; color: #0f172a; }
            .logo span { color: #06b6d4; }
            .success { background: #ecfdf5; border: 1px solid #10b981; padding: 16px; border-radius: 8px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="logo">🚀 <span>FrankTech</span> Intelligence</div>
            <h2>✅ Email Test Successful!</h2>
            <div class="success">
                <p>Your FrankTech email notifications are working correctly.</p>
                <p style="font-size: 14px; color: #475569;">You will receive alerts when critical errors are detected.</p>
            </div>
            <div class="footer" style="margin-top: 20px; padding-top: 20px; border-top: 2px solid #f1f5f9; color: #64748b; text-align: center;">
                <p>FrankTech Intelligence</p>
            </div>
        </div>
    </body>
    </html>
    """)